services:
  traefik:
    container_name: traefik
    image: traefik:2.11
    restart: unless-stopped
    networks:
    - intranet
    ports:
    - 80:80
    - 443:443
    expose:
    - 5001
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./traefik.yml:/etc/traefik/traefik.yml:ro
    - ./dynamic.yml:/rules/dynamic.yml:ro
    - ./users:/users:ro
    - acme:/acme
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVE_ACME_EMAIL: ${EMAIL}
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.service=api@internal"
    - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
    - "traefik.http.routers.traefik.entrypoints=websecure"
    - "traefik.http.routers.traefik.middlewares=admin-auth@file"
  registry:
    container_name: registry
    image: registry:2
    restart: unless-stopped
    networks:
    - intranet
    expose:
    - 5001
    volumes:
    - registry_data:/var/lib/registry
    - ./registry.yml:/etc/docker/registry/config.yml:ro
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN}`)"
    - "traefik.http.routers.registry.entrypoints=websecure"
    - "traefik.http.routers.registry.middlewares=admin-auth@file"

networks:
  intranet:
    external: true

volumes:
  acme:
  registry_data:
    external: true
