entrypoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
  metrics:
    address: ':5001'

certificatesResolvers:
  leresolver:
    acme:
      httpChallenge:
        entryPoint: web
      storage: /acme.json

http:
  routers:
    http-catchall:
      rule: hostregexp(`{host:.+}`)
      entryPoints: web
      middlewares:
      - redirect-to-https
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

log:
  level: INFO
  format: json

metrics:
  prometheus:
    entryPoint: metrics
