entrypoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ':443'
    tls:
      certResolver: leresolve
  metrics:
    address: ':5001'

certificatesResolvers:
  leresolve:
    acme:
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  # routers:
  #   http-catchall:
  #     rule: hostregexp(`{host:.+}`)
  #     entryPoints: web
  #     middlewares:
  #     - redirect-to-https
  middlewares:
    admin-auth:
      basicAuth:
        usersFile: /users/admin
    # redirect-to-https:
    #   redirectScheme:
    #     scheme: https
    #     permanent: true

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

log:
  level: INFO
  format: json

metrics:
  prometheus:
    entryPoint: metrics
