entrypoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: leresolve
  metrics:
    address: ':5001'

certificatesResolvers:
  leresolve:
    acme:
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /rules/dynamic.yml
    watch: false

log:
  level: INFO
  format: json

metrics:
  prometheus:
    entryPoint: metrics
